name: Deploy ADF_Publish to SIT_ADF_Publish

on:
  push:
    branches:
      - adf_publish

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout adf_publish
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ADF ARM Templates to SIT
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.SIT_RESOURCE_GROUP }}
          template: ARMTemplateForFactory.json
          parameters: ARMTemplateParametersForFactory.json
